version: '3'

services:
  postgres:
    image: postgres:16.0
    container_name: postgres-DataCellar
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.2
    container_name: redis-DataCellar
    ports:
      - "6379:6379"

  ganache:
    image: trufflesuite/ganache-cli:v6.12.2
    container_name: blockchain-DataCellar
    volumes:
      - ganache-data:/data
    ports:
      - "8545:8545"
    command: ["-s", "1234", "--defaultBalanceEther", "1000", "--db", "/data", "--gasLimit", "8000000000"]

volumes:
  postgres-data:
  ganache-data: